#!/bin/bash
# Robot environment loader — generated by deploy/install.sh from this template.
# Loads ROS2 Humble, CycloneDDS, CUDA paths, and the MAX-Brain workspace.
# Sourced by start_robot_system.sh on every boot.

echo "========================================"
echo "[ENV LOADER] Starting Environment Setup..."
echo "========================================"

# 1. Source ROS Humble
if [ -f /opt/ros/humble/setup.bash ]; then
    source /opt/ros/humble/setup.bash
    echo "[ENV LOADER] Sourced ROS 2 Humble base."
else
    echo "[ENV LOADER ERROR] /opt/ros/humble/setup.bash not found!"
fi

export PYTHONUNBUFFERED=1
export RCUTILS_LOGGING_BUFFERED_STREAM=0
echo "[ENV LOADER] Set python and ROS logging output buffering to false."

# 2. Configure RMW Middleware to Fast DDS
export ROS_DOMAIN_ID=0
export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
unset CYCLONEDDS_URI

echo "[ENV LOADER] Set RMW to: $RMW_IMPLEMENTATION (ROS_DOMAIN_ID: $ROS_DOMAIN_ID)"

# 3. Setup CUDA & library paths
export PATH=/usr/local/cuda-12.6/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/lib:/usr/local/cuda-12.6/lib64:$LD_LIBRARY_PATH

echo "[ENV LOADER] CUDA 12.6 appended to PATH and LD_LIBRARY_PATH."

# 4. Source the robot workspace
if [ -f /home/rover/rover_workspace/install/setup.bash ]; then
    source /home/rover/rover_workspace/install/setup.bash
    echo "[ENV LOADER] Sourced rover_workspace install overlay."
else
    echo "[ENV LOADER ERROR] /home/rover/rover_workspace/install/setup.bash not found! Has the workspace been built?"
fi

# 5. Summary Debug Output
echo "========================================"
echo "[ENV LOADER] Final Environment Status:"
echo " - ROS_DISTRO        : $ROS_DISTRO"
echo " - RMW_IMPLEMENTATION: $RMW_IMPLEMENTATION"
echo " - ROS_DOMAIN_ID     : $ROS_DOMAIN_ID"
echo " - AMENT_PREFIX_PATH : $AMENT_PREFIX_PATH"
echo "========================================"